spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

fcm:
  service-account-file: fcm-project.json
  project-id: fcm-project-id

management:
  endpoints:
    web:
      exposure:
        include: '*'
