spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/restaurant?useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=true&rewriteBatchedStatements=true
      username: root
      password: 1234

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

fcm:
  service-account-file: alone-test-f8c31-firebase-adminsdk-fbsvc-586c070321.json
  project-id: alone-test

management:
  endpoints:
    web:
      exposure:
        include: '*'
