spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:tcp://localhost/~/study;MODE=MYSQL
    username: sa
    password: 123

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

apis:
  order-api:
    url: http://localhost:8081/providers/order-api/v1/orders
