spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:tcp://localhost/~/study;MODE=MYSQL
    username: sa
    password: 123

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
