spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
