server:
  port: 9010

spring:
  data:
    redis:
      port: 6379
      host: localhost

scheduler:
  enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 63790

scheduler:
  enabled: false
