spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/study;MODE=MYSQL
    username: sa
    password: 123

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10Mb
      location: ~/IdeaProjects/study-project

logging.level:
    org.hibernate.SQL: debug
