INSERT INTO CUSTOMER(NAME) VALUES ('박나경');

INSERT INTO MOVIE(TITLE, FEE) VALUES ('한산', 10000);

INSERT INTO DISCOUNT_POLICY(MOVIE_ID, POLICY_TYPE, AMOUNT, PERCENT) VALUES (1, 'AMOUNT', 1000, NULL);
INSERT INTO DISCOUNT_POLICY(MOVIE_ID, POLICY_TYPE, AMOUNT, PERCENT) VALUES (1, 'PERCENT', NULL, 0.1);

INSERT INTO DISCOUNT_CONDITION(POLICY_ID, CONDITION_TYPE, SEQUENCE, DAY_OF_WEEK, START_TIME, END_TIME) VALUES (1, 'SEQUENCE', 1, NULL, NULL, NULL);
INSERT INTO DISCOUNT_CONDITION(POLICY_ID, CONDITION_TYPE, SEQUENCE, DAY_OF_WEEK, START_TIME, END_TIME) VALUES (1, 'PERIOD', NULL, 'WEDNESDAY', '09:00', '11:30');
INSERT INTO DISCOUNT_CONDITION(POLICY_ID, CONDITION_TYPE, SEQUENCE, DAY_OF_WEEK, START_TIME, END_TIME) VALUES (2, 'SEQUENCE', 1, NULL, NULL, NULL);
INSERT INTO DISCOUNT_CONDITION(POLICY_ID, CONDITION_TYPE, SEQUENCE, DAY_OF_WEEK, START_TIME, END_TIME) VALUES (2, 'PERIOD', NULL, 'WEDNESDAY', '09:00', '11:30');

INSERT INTO SCREENING(MOVIE_ID, SEQUENCE, WHEN_SCREENED) VALUES (1, 1, '2024-11-08 09:00');
