debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com:
      project:
        adminboard: debug
    org:
      springframework:
        web:
          server: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
  thymeleaf3:
    decoupled-logic: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
