services:
  mysql:
    image: mysql:8.0.40
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: chatsystem
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "13306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
