spring:
  datasource:
    jdbc-url: jdbc:h2:tcp://localhost/~/study;MODE=MYSQL
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

mybatis:
  mapper-locations: classpath:com.example.mapper/*.xml
